#!/bin/bash
# Sync Google Calendar ICS files → local vdir for khal

CONF="$HOME/.config/khal/calendars.conf"
VDIR_BASE="$HOME/.local/share/calendars"
KHAL_CONF="$HOME/.config/khal/config"
ICS2VDIR="$HOME/.config/hypr/scripts/ics2vdir.py"
TMPDIR_BASE=$(mktemp -d /tmp/cal-sync-XXXX)
trap "rm -rf $TMPDIR_BASE" EXIT

if [[ ! -f "$CONF" ]]; then
    echo "Error: $CONF not found" >&2
    exit 1
fi

# Collect active calendars for khal config generation
declare -a CAL_NAMES
declare -A CAL_COLORS
errors=0

echo "Syncing calendars..."

while IFS='|' read -r name color url; do
    # Skip comments and empty lines
    [[ -z "$name" || "$name" =~ ^# ]] && continue
    name="${name// /_}"   # spaces → underscores in dir names

    if [[ "$url" == *"REEMPLAZAR"* ]]; then
        echo "  [$name] SKIP — URL not configured"
        continue
    fi

    echo "  [$name] Downloading..."
    tmpfile="$TMPDIR_BASE/${name}.ics"

    if ! curl -sf --max-time 15 "$url" -o "$tmpfile"; then
        echo "  [$name] ERROR — download failed" >&2
        ((errors++))
        continue
    fi

    # Convert ICS → vdir
    if python3 "$ICS2VDIR" "$tmpfile" "$VDIR_BASE/$name" 2>&1; then
        CAL_NAMES+=("$name")
        CAL_COLORS["$name"]="$color"
    else
        echo "  [$name] ERROR — ICS conversion failed" >&2
        ((errors++))
    fi

done < "$CONF"

# Regenerate khal [calendars] section
# Keep everything above the marker, replace from marker down
MARKER="# --- AUTO-GENERATED by calendar-sync.sh ---"

if [[ -f "$KHAL_CONF" ]]; then
    base_conf="$(awk "/$MARKER/{exit} {print}" "$KHAL_CONF")"
else
    base_conf=""
fi

{
    echo "$base_conf"
    echo "$MARKER"
    echo "[calendars]"
    for name in "${CAL_NAMES[@]}"; do
        color="${CAL_COLORS[$name]}"
        echo ""
        echo "[[${name}]]"
        echo "path = $VDIR_BASE/$name/"
        echo "color = $color"
        echo "readonly = True"
    done
} > "$KHAL_CONF.tmp" && mv "$KHAL_CONF.tmp" "$KHAL_CONF"

echo "Done. Calendars synced: ${#CAL_NAMES[@]}, errors: $errors"
[[ $errors -gt 0 ]] && exit 1 || exit 0
