# -----------------------------------------------------
# Autostart Configuration
# -----------------------------------------------------

# Waybar
exec-once = waybar

# Wallpaper daemon + restaurar fondo
exec-once = awww-daemon && awww img ~/Pictures/wallpapers/lofirain.png

# Notification daemon
exec-once = swaync

# Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Idle daemon
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --watch cliphist store

# Inicializar workspaces en los monitores correctos
exec-once = ~/.config/hypr/scripts/init-workspaces.sh
