# -----------------------------------------------------
# Cursor Configuration
# -----------------------------------------------------

cursor {
    no_hardware_cursors = false
    hide_on_key_press = false
}
