# -----------------------------------------------------
# Monitors Configuration
# -----------------------------------------------------

# DP-1 (ASUS VA27EHF) - arriba izquierda
monitor = DP-1, 1920x1080@100.05, 0x0, 1

# HDMI-A-1 (SAC LED MONITOR) - arriba derecha
monitor = HDMI-A-1, 1920x1080@74.97, 1920x1080, 1

# eDP-1 (laptop) - abajo del DP-1
monitor = eDP-1, preferred, 3840x2160, 1.25

# Si solo tienes un monitor, usa:
# monitor = , preferred, auto, 1
