# -----------------------------------------------------
# Windowrules Configuration
# -----------------------------------------------------

# Rofi - blur on layer surface
layerrule {
    name = rofi-blur
    match:namespace = ^rofi$
    blur = true
}

# AGS calendar popup - floating centered
windowrule {
    name = ags-calendar-float
    match:class = ^com\.github\.Aylur\.ags$
    match:title = ^calendar$
    float = true
    center = true
}

# Ignore maximize requests
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix XWayland dragging
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
